AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  DungeonQuestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: DungeonQuestApi
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date'"
        AllowOrigin: "'*'"

  DungeonQuestMainFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DungeonQuestMainFunction
      CodeUri: .
      Handler: davidmarino.StreamLambdaHandler::handleRequest
      Runtime: java21
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Architectures:
        - arm64
      MemorySize: 512
      Timeout: 30
      Events:
        DungeonQuestApiPost:
          Type: Api
          Properties:
            RestApiId: !Ref DungeonQuestApi
            Path: /dungeonquest
            Method: post

        ArtifactSubcategoriesGet:
          Type: Api
          Properties:
            RestApiId: !Ref DungeonQuestApi
            Path: /artifact-subcategories
            Method: get

        MajorCharactersGet:
          Type: Api
          Properties:
            RestApiId: !Ref DungeonQuestApi
            Path: /major-characters
            Method: get

        MonsterCategoriesGet:
          Type: Api
          Properties:
            RestApiId: !Ref DungeonQuestApi
            Path: /monster-categories
            Method: get