name: Build and Deploy to AWS Lambda
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Maven
        run: mvn clean package -DskipTests
      - name: Upload to AWS Lambda
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: ${{ secrets.LAMBDA_FUNCTION_NAME }}
          region: ${{ secrets.AWS_REGION }}
          zip-file: target/DungeonQuest-v1.0.0.jar
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}